import {
  LayoutDashboard,
  MapPin,
  Calendar,
  Users,
  Target,
  Bike,
  Wrench,
  Headset,
  UsersRound,
  UserCheck,
  CreditCard,
  ShieldAlert,
  ListTodo,
  MessageCircle,
  Blocks,
} from 'lucide-react'

// Using explicit imports instead of wildcard to prevent memory bloat during builds
export const navigation = [
  { name: 'dashboard', href: '/', icon: LayoutDashboard },
  { name: 'hubs', href: '/hubs', icon: MapPin },
  { name: 'calendar', href: '/calendar', icon: Calendar },
  { name: 'crm', href: '/crm', icon: Users },
  { name: 'marketing', href: '/marketing', icon: Target },
  { name: 'fleet', href: '/bikes', icon: Bike },
  { name: 'maintenance', href: '/maintenance', icon: Wrench },
  { name: 'customer_service', href: '/customer-service', icon: Headset },
  { name: 'community', href: '/community', icon: UsersRound },
  { name: 'deliverers', href: '/deliverers', icon: UserCheck },
  { name: 'financial', href: '/financial', icon: CreditCard },
  { name: 'security', href: '/security', icon: ShieldAlert },
  { name: 'tasks', href: '/tasks', icon: ListTodo },
  { name: 'chat', href: '/chat', icon: MessageCircle },
  { name: 'integrations', href: '/integrations', icon: Blocks },
]
