import {
  LayoutDashboard,
  KanbanSquare,
  Megaphone,
  Wrench,
  Headset,
  ShieldAlert,
  DollarSign,
  Brain,
  Settings,
  Bike,
  Building2,
  Package,
  Users,
} from 'lucide-react'

export const navHierarchy = [
  {
    title: 'Visão Geral',
    icon: LayoutDashboard,
    items: [
      { title: 'Dashboard Executivo', url: '/' },
      { title: 'Painel de Hubs', url: '/hubs' },
      { title: 'Alertas Críticos', url: '/security' },
      { title: 'Agenda Operacional', url: '/calendar' },
      { title: 'Agenda Executiva', url: '/calendar' },
    ],
  },
  {
    title: 'Comercial',
    icon: KanbanSquare,
    items: [
      { title: 'CRM', url: '/crm' },
      { title: 'Leads', url: '/crm' },
      { title: 'Pipeline de Vendas', url: '/crm' },
      { title: 'Contratos', url: '/crm' },
      { title: 'Documentos', url: '/crm' },
      { title: 'Parceiros Comerciais', url: '/community' },
    ],
  },
  {
    title: 'Marketing',
    icon: Megaphone,
    items: [
      { title: 'Performance', url: '/marketing' },
      { title: 'Campanhas', url: '/marketing' },
      { title: 'Criativos', url: '/marketing' },
      { title: 'Públicos', url: '/marketing' },
      { title: 'Experimentos', url: '/marketing' },
      { title: 'Analytics', url: '/marketing' },
    ],
  },
  {
    title: 'Frota',
    icon: Bike,
    items: [
      { title: 'Todas as Bikes', url: '/bikes' },
      { title: 'Bikes em Uso', url: '/bikes' },
      { title: 'Bikes em Manutenção', url: '/bikes' },
      { title: 'Bikes Paradas', url: '/bikes' },
      { title: 'Telemetria', url: '/bikes' },
    ],
  },
  {
    title: 'Hubs',
    icon: Building2,
    items: [
      { title: 'Painel dos Hubs', url: '/hubs' },
      { title: 'Agenda do Hub', url: '/calendar' },
      { title: 'Retiradas', url: '/hubs' },
      { title: 'Devoluções', url: '/hubs' },
      { title: 'Ordens de Serviço', url: '/maintenance' },
      { title: 'Relatórios', url: '/hubs' },
    ],
  },
  {
    title: 'Manutenção',
    icon: Wrench,
    items: [
      { title: 'Ordens de Serviço', url: '/maintenance' },
      { title: 'Revisões', url: '/maintenance' },
      { title: 'Diagnóstico', url: '/maintenance' },
      { title: 'Histórico Técnico', url: '/maintenance' },
    ],
  },
  {
    title: 'Supply',
    icon: Package,
    items: [
      { title: 'Estoque Global', url: '/maintenance' },
      { title: 'Estoque por Hub', url: '/maintenance' },
      { title: 'Peças', url: '/maintenance' },
      { title: 'Consumo', url: '/maintenance' },
      { title: 'Reposição', url: '/maintenance' },
      { title: 'Transferências', url: '/maintenance' },
    ],
  },
  {
    title: 'Comunidade',
    icon: Users,
    items: [
      { title: 'Entregadores', url: '/deliverers' },
      { title: 'Pedala Junto', url: '/community' },
      { title: 'Score de Engajamento', url: '/community' },
      { title: 'Benefícios', url: '/community' },
      { title: 'Histórico do Entregador', url: '/deliverers' },
    ],
  },
  {
    title: 'Atendimento',
    icon: Headset,
    items: [
      { title: 'Conversas', url: '/customer-service' },
      { title: 'Chamados', url: '/customer-service' },
      { title: 'SLA', url: '/customer-service' },
      { title: 'Histórico de Atendimento', url: '/customer-service' },
      { title: 'Automação', url: '/customer-service' },
    ],
  },
  {
    title: 'Segurança e Risco',
    icon: ShieldAlert,
    items: [
      { title: 'Incidentes', url: '/security' },
      { title: 'Sinistros', url: '/security' },
      { title: 'BO', url: '/security' },
      { title: 'Fraude', url: '/security' },
      { title: 'Recuperação de Ativos', url: '/security' },
    ],
  },
  {
    title: 'Financeiro',
    icon: DollarSign,
    items: [
      { title: 'Receitas', url: '/financial' },
      { title: 'Cobranças', url: '/financial' },
      { title: 'Inadimplência', url: '/financial' },
      { title: 'Fluxo de Caixa', url: '/financial' },
      { title: 'Contas Bancárias', url: '/financial' },
      { title: 'Conciliação', url: '/financial' },
      { title: 'Relatórios', url: '/financial' },
    ],
  },
  {
    title: 'Inteligência',
    icon: Brain,
    items: [
      { title: 'Analytics Global', url: '/' },
      { title: 'Tendências', url: '/' },
      { title: 'Previsões', url: '/' },
      { title: 'Insights Automáticos', url: '/' },
      { title: 'Modelos Preditivos', url: '/' },
    ],
  },
  {
    title: 'Administração',
    icon: Settings,
    items: [
      { title: 'Usuários', url: '/' },
      { title: 'Permissões', url: '/' },
      { title: 'Hubs', url: '/hubs' },
      { title: 'Integrações Google', url: '/integrations' },
      { title: 'Logs', url: '/tasks' },
      { title: 'Auditoria', url: '/tasks' },
      { title: 'Configurações', url: '/' },
    ],
  },
]
