import { useParams } from 'react-router-dom'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { useToast } from '@/hooks/use-toast'
import {
  User,
  FileText,
  MessageSquare,
  AlertTriangle,
  Copy,
  UploadCloud,
  Link as LinkIcon,
  DollarSign,
} from 'lucide-react'
import { MOCK_CRM_LEADS } from '@/lib/mock-data'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'

export default function LeadDetail() {
  const { id } = useParams()
  const { toast } = useToast()
  const lead = MOCK_CRM_LEADS.find((l) => l.id === id) || MOCK_CRM_LEADS[0]

  const handleExportBO = () => {
    const summary =
      `B.O. Report - Be Bike\nName: ${lead.name}\nCPF: ${lead.cpf || 'N/A'}\nRG: ${lead.rg || 'N/A'}\nAddress: ${lead.address || 'N/A'}\nStatus: ${lead.contractStatus || 'N/A'}\n---\nExport generated by Command Center.`.substring(
        0,
        1400,
      )
    navigator.clipboard.writeText(summary)
    toast({
      title: 'Exportado para B.O.',
      description: 'Resumo copiado para a área de transferência (Max 1400 char).',
    })
  }

  const clientInfoFields = [
    { label: 'Type', value: lead.type || 'N/A' },
    { label: 'CPF', value: lead.cpf || 'N/A' },
    { label: 'RG', value: lead.rg || 'N/A' },
    { label: 'Gender', value: lead.gender || 'N/A' },
    { label: 'DOB', value: lead.dob || 'N/A' },
    { label: 'Civil Status', value: lead.civilStatus || 'N/A' },
    { label: 'Parents', value: lead.parentsNames || 'N/A' },
    { label: 'Address', value: lead.address || 'N/A' },
    { label: 'CEP', value: lead.cep || 'N/A' },
    { label: 'UF', value: lead.uf || 'N/A' },
  ]

  return (
    <div className="space-y-6 max-w-6xl mx-auto pb-12">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white p-6 rounded-xl border shadow-sm">
        <div className="flex items-center gap-4">
          <div className="h-16 w-16 rounded-full bg-primary/10 flex items-center justify-center text-primary border border-primary/20">
            <User className="h-8 w-8" />
          </div>
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-secondary flex items-center gap-3">
              {lead.name}
              <Badge variant="outline" className="bg-muted/50">
                {lead.stage}
              </Badge>
            </h1>
            <p className="text-muted-foreground font-mono text-sm mt-1">{lead.phone}</p>
          </div>
        </div>
        <div className="flex gap-2 w-full sm:w-auto">
          <Button variant="outline" className="gap-2 flex-1 sm:flex-none" asChild>
            <a href={`https://wa.me/55${lead.phone}`} target="_blank" rel="noopener noreferrer">
              <MessageSquare className="w-4 h-4" /> Cloud Humans / WA
            </a>
          </Button>
          <Button
            variant="destructive"
            className="gap-2 flex-1 sm:flex-none"
            onClick={handleExportBO}
          >
            <AlertTriangle className="w-4 h-4" /> B.O. Export
          </Button>
        </div>
      </div>

      <Tabs defaultValue="master" className="w-full">
        <TabsList className="grid w-full max-w-2xl grid-cols-4">
          <TabsTrigger value="master">360º Master</TabsTrigger>
          <TabsTrigger value="contract">Contratos</TabsTrigger>
          <TabsTrigger value="performance">Performance</TabsTrigger>
          <TabsTrigger value="files">Arquivos</TabsTrigger>
        </TabsList>

        <TabsContent value="master" className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Client Info</CardTitle>
              <CardDescription>Dados cadastrais unificados.</CardDescription>
            </CardHeader>
            <CardContent className="grid grid-cols-2 gap-y-4 gap-x-2">
              {clientInfoFields.map((field) => (
                <div
                  key={field.label}
                  className={
                    field.label === 'Address' || field.label === 'Parents' ? 'col-span-2' : ''
                  }
                >
                  <p className="text-xs text-muted-foreground uppercase tracking-wider mb-1">
                    {field.label}
                  </p>
                  <p className="font-medium text-sm text-secondary">{field.value}</p>
                </div>
              ))}
            </CardContent>
          </Card>

          <div className="space-y-6">
            <Card className="bg-slate-50 border-slate-200">
              <CardHeader className="pb-3">
                <CardTitle className="text-lg flex items-center gap-2">
                  <DollarSign className="w-4 h-4 text-slate-500" /> Financial & Contract Status
                </CardTitle>
              </CardHeader>
              <CardContent>
                <Badge
                  className="text-sm px-3 py-1 mb-4"
                  variant={lead.contractStatus === 'Vigente' ? 'default' : 'secondary'}
                >
                  {lead.contractStatus || 'Sem contrato'}
                </Badge>
                <div className="text-sm text-muted-foreground">
                  Integração AsaaS:{' '}
                  <span className="font-semibold text-emerald-600">Adimplente</span>
                </div>
              </CardContent>
            </Card>

            <Card className="border-red-100 bg-red-50/50">
              <CardHeader className="pb-3">
                <CardTitle className="text-lg text-red-700 flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4" /> Delegacia Eletrônica
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-red-600/80 mb-4">
                  Acesso rápido para registro de ocorrência com os dados do locatário.
                </p>
                <Button
                  variant="outline"
                  className="w-full border-red-200 text-red-700 hover:bg-red-100"
                  asChild
                >
                  <a
                    href="https://www.delegaciaeletronica.policiacivil.sp.gov.br/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <ExternalLink className="w-4 h-4 mr-2" /> Abrir SP Polícia Civil
                  </a>
                </Button>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="contract" className="mt-6">
          <Card>
            <CardHeader>
              <CardTitle>ZapSign Integration</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between p-4 border rounded-lg bg-muted/20">
                <div className="flex items-center gap-3">
                  <FileText className="w-5 h-5 text-primary" />
                  <div>
                    <p className="font-medium">Contrato de Locação Padrão</p>
                    <p className="text-xs text-muted-foreground">Enviado em 10/05/2024</p>
                  </div>
                </div>
                <Badge variant="outline" className="border-primary text-primary">
                  Assinado
                </Badge>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="performance" className="mt-6">
          <Card>
            <CardHeader>
              <CardTitle>99Food Performance</CardTitle>
              <CardDescription>Faça upload das planilhas para atualizar o score.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="border-2 border-dashed rounded-xl p-10 flex flex-col items-center justify-center text-center bg-muted/10 hover:bg-muted/30 transition-colors cursor-pointer">
                <UploadCloud className="w-10 h-10 text-muted-foreground mb-4" />
                <h3 className="font-semibold mb-1">Arraste a planilha CSV/Excel aqui</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Provisório até ativação da API direta.
                </p>
                <Button variant="secondary" size="sm">
                  Procurar Arquivo
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="files" className="mt-6">
          <Card>
            <CardContent className="pt-6">
              <div className="text-center py-10 text-muted-foreground">
                <p>Área de drop para CNH, Comprovante de Residência e Apólices.</p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}
